module.exports.soundFiles = [
"sound/Mixed_Fx_Sounds/90 Realm.wav",
"sound/Mixed_Fx_Sounds/91 Twisted.wav",
"sound/Mixed_Fx_Sounds/92 Ghosts.wav",
"sound/Noises/Analogue Hiss Lo Boost.aif",
"sound/Noises/Analogue Hiss Lo Cut.aif",
"sound/Noises/Analogue Hiss Mid Boost.aif",
"sound/Noises/Crackle Pops.aif",
"sound/Noises/Crunchy Crackle.aif",
"sound/Noises/Fake Vinyl 1.aif",
"sound/Noises/Fake Vinyl 2.aif",
"sound/Noises/FizzPop.aif",
"sound/S7_recordings/S7_1.m4a",
"sound/S7_recordings/S7_2.m4a",
"sound/S7_recordings/S7_3.m4a",
"sound/S7_recordings/S7_4.m4a",
"sound/iPad_FX_Samples/sample_1-1.wav",
"sound/iPad_FX_Samples/sample_1-2.wav",
"sound/iPad_FX_Samples/sample_1-3.wav",
"sound/iPad_FX_Samples/sample_1-4.wav",
"sound/iPad_FX_Samples/sample_1-5.wav",
"sound/iPad_FX_Samples/sample_2-1.wav",
"sound/iPad_FX_Samples/sample_2-2.wav",
"sound/iPad_FX_Samples/sample_2-3.wav",
"sound/iPad_FX_Samples/sample_2-4.wav",
"sound/iPad_FX_Samples/sample_2-5.wav",
"sound/iPad_FX_Samples/sample_3-1.wav",
"sound/iPad_FX_Samples/sample_3-2.wav",
"sound/iPad_FX_Samples/sample_3-3.wav",
"sound/iPad_FX_Samples/sample_3-4.wav",
"sound/iPad_FX_Samples/sample_3-5.wav",
"sound/iPad_FX_Samples/sample_4-1.wav",
"sound/iPad_FX_Samples/sample_4-2.wav",
"sound/iPad_FX_Samples/sample_4-3.wav",
"sound/iPad_FX_Samples/sample_4-4.wav",
"sound/iPad_FX_Samples/sample_4-5.wav",
]
